version: 2
jobs:
  build:
    docker:
      - image: pubnative/android_15

    working_directory: ~/driller

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout
      - restore_cache:
          key: sdk-{{ .Branch }}
      - run:
          name: Run Tests
          command: ./gradlew clean testDebug
      - run:
          name: Send reports to coveralls.io
          command: ./gradlew cobertura coveralls
      - save_cache:
          key: sdk-{{ .Branch }}
          paths:
            - "/usr/local/android-sdk"
      - deploy:
          name: Deploy to Bintray
          command: |
            ./gradlew bintrayUpload